### PR TITLE
use normalized package name with hyphens instead of dots

### PR DESCRIPTION
**Pull request by NiklasRosenstein**

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
cc @super-secret-github-user

**Comment by NiklasRosenstein** [comment]
Actually, this will fail applications that depend on the old name and somehow use `pkg_resources`, e.g. by defining console scripts.

Example from the fallout of renaming `nr.util` to `nr-util` when running the `slap` command that depends on the `nr.util` package:

image

Even though the package is installed as expected by PyPI, `pkg_resources` will fail to understand that `nr.util` is the same as `nr-util`.

**Comment by ghost** [comment]
so is slap here still trying to fetch "nr.util" as opposed to "nr-util"? How is the dependency listed in slap's pyproject.toml?

**Comment by NiklasRosenstein** [comment]
It's not Slap's fault. It has a dependency on `nr.util`, and when Slap is installed Pip installs the latest matching version matching the version constraint for that dependency. If that package actually is called `nr-util` in it's metadata, that's what the package is installed as into the environment instead of `nr.util`.

Slap also defines a console script as an entry point in its `pyproject.toml`. When that entry point is resolved, it uses the `pkg_resources` module which comes as part of the `setuptools` package. There is some logic in this step module to ensure that all the dependencies required by the application are satisfied. This is where it breaks down: `pkg_resources` seems Slap depending on `nr.util` but does not find it because the package was installed as `nr-util`.

**Pull request closed without merging**
